### ISSUE TITLE
Bug/Home screen can get stuck on mobile

### ISSUE THREAD

**Issue by yarkhinephyo** [nandium/RouteMaker#74]
#### Problem
On mobile, after uploading the photo and scrolling down, user may find difficulty scrolling back up. This is due to the fact that the HTML canvas containing the uploaded photo responds to the finger scrolling up by shifting the image within the frame.
(Shifting the image within the frame is an intended feature)

#### Possible solution
Modify the canvas listener so that when the user drags up the canvas, the screen gets scrolled up instead (When image can no longer be shifted up due to boundary constraints)

Only needs to modify tap listener, not click listener.

Possibly modify this function (Single finger canvas listener)?
https://github.com/yarkhinephyo/yolo_bouldering/blob/182ee8aeb930589526e89da24cdd2323ece6878b/ionic_user_interface/src/components/wall-image-viewer/stageListeners.ts#L125

#### Possible challenge
It is difficult to test on mobile browser. What I did was, I hosted on another github repo for myself to test. I think you can skip step 2, 3 if you host on like Netlify.

1. Add the endpoints in `ionic_user_interface/.env.development.local` into `ionic_user_interface/.env.production.local`
2. Add a new env variable called `VUE_APP_PRODUCTION_ROUTE=/{repo_name}`
3. Replace `{repo_name}` with your repo name
4. `npm run build`
5. Deploy the build directory

Don't have to follow this. If you have a better way to test for mobile browser, it will be good.

**Comment by joenchua** [comment]
!

**Comment by yarkhinephyo** [comment]
To simulate touch in a browser (Found it personally useful maybe there are better options)

https://hammerjs.github.io/touch-emulator/

Scroll down to "Bookmarklet"
